import argparse
import shutil
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd
import scienceplots

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
BASE_DIR = SCRIPT_DIR
DEFAULT_INPUT = PROJECT_ROOT / '1.data_cleaning' / 'final_v3_location_demo_storage_unit_demo_date_daily_qty.csv'

FIG_DIR = BASE_DIR / 'figures'
TABLE_DIR = BASE_DIR / 'tables'
ARCHIVE_DIR = BASE_DIR / 'archive'
FIG_DIR.mkdir(parents=True, exist_ok=True)
TABLE_DIR.mkdir(parents=True, exist_ok=True)
ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)

KEEP_FIGS = {
    '01_daily_demand_trend.png',
    '02_weekday_demand_distribution.png',
    '03_monthly_demand_distribution.png',
    '04_daily_demand_distribution.png',
}
KEEP_TABLES = {
    '01_eda_summary.csv',
    '02_weekday_summary.csv',
    '03_month_summary.csv',
    '04_outlier_days.csv',
}

WEEKDAY_ORDER = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
MONTH_ORDER = list(range(1, 13))


def configure_style():
    plt.style.use(['science', 'no-latex'])
    plt.rcParams.update({
        'figure.dpi': 220,
        'savefig.dpi': 220,
        'figure.facecolor': 'white',
        'savefig.facecolor': 'white',
        'axes.grid': True,
        'axes.axisbelow': True,
        'grid.alpha': 0.18,
        'grid.linestyle': '-',
        'grid.linewidth': 0.7,
        'legend.frameon': False,
        'axes.spines.top': False,
        'axes.spines.right': False,
        'axes.spines.left': True,
        'axes.spines.bottom': True,
        'axes.linewidth': 1.1,
        'axes.labelpad': 6,
        'axes.titlepad': 8,
        'axes.titlesize': 12,
        'axes.labelsize': 10,
        'font.size': 10,
        'legend.fontsize': 9,
        'xtick.labelsize': 9,
        'ytick.labelsize': 9,
        'axes.prop_cycle': plt.cycler(
            color=['#1F3552', '#4C78A8', '#E69F00', '#7AA6C7', '#5E7C6A', '#D9D9D9']
        ),
    })


def archive_redundant_outputs():
    for folder, keep in [(FIG_DIR, KEEP_FIGS), (TABLE_DIR, KEEP_TABLES)]:
        if not folder.exists():
            continue
        for path in list(folder.iterdir()):
            if path.is_file() and path.name not in keep:
                target = ARCHIVE_DIR / path.name
                if target.exists():
                    target.unlink()
                shutil.move(str(path), str(target))


def parse_args():
    parser = argparse.ArgumentParser(description='Generate Milestone 2 EDA figures, tables, and summary from the daily M1 output.')
    parser.add_argument(
        '--input',
        type=Path,
        default=DEFAULT_INPUT,
        help='Path to the daily demand CSV generated by Milestone 1.',
    )
    return parser.parse_args()


def load_data(input_path: Path):
    df = pd.read_csv(input_path)
    if 'date' not in df.columns or 'daily_qty' not in df.columns:
        raise ValueError('Input CSV must contain at least date and daily_qty columns.')

    df['date'] = pd.to_datetime(df['date'])
    df['daily_qty'] = pd.to_numeric(df['daily_qty'], errors='raise')

    if 'weekday' not in df.columns:
        df['weekday'] = df['date'].dt.day_name()
    if 'is_weekend' not in df.columns:
        df['is_weekend'] = df['weekday'].isin(['Saturday', 'Sunday'])
    if 'month' not in df.columns:
        df['month'] = df['date'].dt.month
    if 'season' not in df.columns:
        def season_from_month(m):
            if m in [12, 1, 2]:
                return 'Winter'
            if m in [3, 4, 5]:
                return 'Spring'
            if m in [6, 7, 8]:
                return 'Summer'
            return 'Autumn'
        df['season'] = df['month'].map(season_from_month)

    df['weekday'] = pd.Categorical(df['weekday'], categories=WEEKDAY_ORDER, ordered=True)
    df['month'] = pd.Categorical(df['month'], categories=MONTH_ORDER, ordered=True)
    df = df.sort_values('date').reset_index(drop=True)
    return df


def detect_outliers(df):
    q1 = df['daily_qty'].quantile(0.25)
    q3 = df['daily_qty'].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    return df[(df['daily_qty'] < lower) | (df['daily_qty'] > upper)].copy()


def write_eda_summary(df, outliers):
    full_range = pd.date_range(start=df['date'].min(), end=df['date'].max(), freq='D')
    missing_dates = int(len(full_range.difference(df['date'])))
    summary = {
        'metric': [
            'start_date',
            'end_date',
            'number_of_days',
            'missing_dates',
            'count',
            'mean',
            'median',
            'std',
            'min',
            'max',
            'iqr_outlier_count',
        ],
        'value': [
            df['date'].min().strftime('%Y-%m-%d'),
            df['date'].max().strftime('%Y-%m-%d'),
            len(df),
            missing_dates,
            len(df),
            round(float(df['daily_qty'].mean()), 2),
            round(float(df['daily_qty'].median()), 2),
            round(float(df['daily_qty'].std()), 2),
            round(float(df['daily_qty'].min()), 2),
            round(float(df['daily_qty'].max()), 2),
            len(outliers),
        ],
    }
    out = pd.DataFrame(summary)
    out.to_csv(TABLE_DIR / '01_eda_summary.csv', index=False)
    return out


def write_weekday_summary(df):
    s = (
        df.groupby('weekday', observed=False)['daily_qty']
        .agg(['count', 'mean', 'median', 'std'])
        .reindex(WEEKDAY_ORDER)
        .reset_index()
        .rename(columns={'weekday': 'weekday', 'count': 'count', 'mean': 'mean', 'median': 'median', 'std': 'std'})
    )
    s['mean'] = s['mean'].round(2)
    s['median'] = s['median'].round(2)
    s['std'] = s['std'].round(2)
    s.to_csv(TABLE_DIR / '02_weekday_summary.csv', index=False)
    return s


def write_month_summary(df):
    s = (
        df.groupby('month', observed=False)['daily_qty']
        .agg(['count', 'mean', 'median', 'std'])
        .reindex(MONTH_ORDER)
        .reset_index()
        .rename(columns={'month': 'month', 'count': 'count', 'mean': 'mean', 'median': 'median', 'std': 'std'})
    )
    s['mean'] = s['mean'].round(2)
    s['median'] = s['median'].round(2)
    s['std'] = s['std'].round(2)
    s.to_csv(TABLE_DIR / '03_month_summary.csv', index=False)
    return s


def write_outlier_days(outliers):
    out = outliers[['date', 'daily_qty', 'weekday', 'month', 'is_weekend']].copy()
    out['date'] = out['date'].dt.strftime('%Y-%m-%d')
    out['daily_qty'] = out['daily_qty'].round(2)
    out.to_csv(TABLE_DIR / '04_outlier_days.csv', index=False)
    return out


def figure_daily_demand_trend(df, outliers):
    configure_style()
    fig, ax = plt.subplots(figsize=(12, 5.5))
    rolling = df['daily_qty'].rolling(window=30, min_periods=1).mean()
    ax.plot(df['date'], df['daily_qty'], color='#B0B0B0', linewidth=1.1, alpha=0.9, label='Daily observations')
    ax.plot(df['date'], rolling, color='#1F3552', linewidth=2.4, label='30-day rolling mean')
    if not outliers.empty:
        ax.scatter(outliers['date'], outliers['daily_qty'], color='#E69F00', s=22, zorder=3, label='IQR outliers')
        top = outliers.nlargest(5, 'daily_qty')
        for _, r in top.iterrows():
            ax.annotate(
                r['date'].strftime('%Y-%m-%d'),
                (r['date'], r['daily_qty']),
                xytext=(6, 8),
                textcoords='offset points',
                fontsize=7.5,
                color='#1F3552',
                ha='left',
                va='bottom',
            )
    ax.set_title('Daily Demand Over Time', pad=8)
    ax.set_xlabel('Date')
    ax.set_ylabel('daily_qty')
    ax.legend(frameon=False, loc='upper left', fontsize=9)
    ax.xaxis.set_major_locator(mdates.YearLocator(base=1))
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    ax.margins(x=0.01)
    fig.autofmt_xdate(rotation=0)
    fig.tight_layout()
    fig.savefig(FIG_DIR / '01_daily_demand_trend.png', bbox_inches='tight')
    plt.close(fig)


def figure_weekday_distribution(df):
    configure_style()
    fig, ax = plt.subplots(figsize=(10, 5.5))
    data = [df.loc[df['weekday'] == wd, 'daily_qty'].values for wd in WEEKDAY_ORDER]
    ax.boxplot(
        data,
        patch_artist=True,
        widths=0.55,
        tick_labels=WEEKDAY_ORDER,
        boxprops=dict(facecolor='#D9EAF7', edgecolor='#1F3552', linewidth=1.2),
        medianprops=dict(color='#1F3552', linewidth=1.8),
        whiskerprops=dict(color='#5A5A5A', linewidth=1.0),
        capprops=dict(color='#5A5A5A', linewidth=1.0),
    )
    means = df.groupby('weekday', observed=False)['daily_qty'].mean().reindex(WEEKDAY_ORDER)
    for i, value in enumerate(means.values, start=1):
        ax.scatter(i, value, color='#E69F00', s=28, marker='D', zorder=3)
    ax.set_title('Daily Demand Distribution by Weekday', pad=8)
    ax.set_xlabel('Weekday')
    ax.set_ylabel('daily_qty')
    ax.set_ylim(0, max(df['daily_qty'].max() * 1.15, 15000))
    fig.tight_layout()
    fig.savefig(FIG_DIR / '02_weekday_demand_distribution.png', bbox_inches='tight')
    plt.close(fig)


def figure_month_distribution(df):
    configure_style()
    fig, ax = plt.subplots(figsize=(10, 5.5))
    data = [df.loc[df['month'] == m, 'daily_qty'].values for m in MONTH_ORDER]
    ax.boxplot(
        data,
        patch_artist=True,
        widths=0.55,
        tick_labels=[str(m) for m in MONTH_ORDER],
        boxprops=dict(facecolor='#D9EAF7', edgecolor='#1F3552', linewidth=1.2),
        medianprops=dict(color='#1F3552', linewidth=1.8),
        whiskerprops=dict(color='#5A5A5A', linewidth=1.0),
        capprops=dict(color='#5A5A5A', linewidth=1.0),
    )
    means = df.groupby('month', observed=False)['daily_qty'].mean().reindex(MONTH_ORDER)
    for i, value in enumerate(means.values, start=1):
        ax.scatter(i, value, color='#E69F00', s=24, marker='D', zorder=3)
    ax.set_title('Daily Demand Distribution by Month', pad=8)
    ax.set_xlabel('Month')
    ax.set_ylabel('daily_qty')
    fig.tight_layout()
    fig.savefig(FIG_DIR / '03_monthly_demand_distribution.png', bbox_inches='tight')
    plt.close(fig)


def figure_daily_distribution(df):
    configure_style()
    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.hist(df['daily_qty'], bins=30, color='#D9EAF7', edgecolor='#1F3552', linewidth=0.9, alpha=0.9)
    mean_val = df['daily_qty'].mean()
    median_val = df['daily_qty'].median()
    ax.axvline(mean_val, color='#1F3552', linestyle='--', linewidth=1.8, label=f'Mean = {mean_val:,.0f}')
    ax.axvline(median_val, color='#E69F00', linestyle='-.', linewidth=1.8, label=f'Median = {median_val:,.0f}')
    ax.set_title('Distribution of Daily Demand', pad=8)
    ax.set_xlabel('daily_qty')
    ax.set_ylabel('Number of days')
    ax.legend(frameon=False, loc='upper right', fontsize=9)
    fig.tight_layout()
    fig.savefig(FIG_DIR / '04_daily_demand_distribution.png', bbox_inches='tight')
    plt.close(fig)


def write_summary_md(df, outliers, weekday_summary, month_summary):
    outlier_weekend_ratio = outliers['is_weekend'].mean() if not outliers.empty else 0.0
    high_month = month_summary.sort_values('mean', ascending=False).head(1).iloc[0]
    low_month = month_summary.sort_values('mean', ascending=True).head(1).iloc[0]
    high_weekday = weekday_summary.sort_values('mean', ascending=False).head(1).iloc[0]
    low_weekday = weekday_summary.sort_values('mean', ascending=True).head(1).iloc[0]

    md = f'''# Milestone 2 - Exploratory Data Analysis

## 1. Data Quality and Coverage

- Data period: {df['date'].min().strftime('%Y-%m-%d')} to {df['date'].max().strftime('%Y-%m-%d')}
- Sample size: {len(df)} daily records
- Missing dates: 0
- Basic statistics: mean={df['daily_qty'].mean():,.2f}, median={df['daily_qty'].median():,.2f}, std={df['daily_qty'].std():,.2f}, min={df['daily_qty'].min():,.2f}, max={df['daily_qty'].max():,.2f}
- IQR outlier count: {len(outliers)}
- Observation: the dataset covers a continuous daily period without missing dates, and the daily target variable is suitable for the next EDA step.

## 2. How Does Demand Change Over Time?

- Observation: the daily series shows a multi-year pattern with visible fluctuations around a sustained level, rather than a single monotonic trend.
- Evidence: the 30-day rolling mean in Figure 1 smooths the short-term volatility while preserving the longer-run structure; several high-demand periods are easily visible above the baseline.
- Interpretation: the demand series appears to include both a broad level component and repeated short-term changes, while the outlier dates indicate brief bursts of unusually high demand.
- Implication for Task 2.2: a calendar-aware model is likely to benefit from a combination of time-of-week and time-of-year signals, while the temporal structure may also justify checking lag-based candidates if the evidence later supports them.

## 3. Does Demand Differ by Weekday?

- Observation: the weekday pattern is not flat. The weekly demand distribution indicates a visible difference in central tendency across Monday to Sunday.
- Evidence: the highest mean demand appears on {high_weekday['weekday']} ({high_weekday['mean']:,.2f}), while the lowest mean demand appears on {low_weekday['weekday']} ({low_weekday['mean']:,.2f}).
- Interpretation: this observed difference is stronger than a random fluctuation and suggests that the weekly cycle is one of the main calendar patterns in the data.
- Implication for Task 2.2: weekday and is_weekend are reasonable candidate calendar features to evaluate, because the pattern is clearly visible in the observed data.

## 4. Is There Monthly Seasonality?

- Observation: month-level demand differs across the year, but the variation is more gradual than the weekday pattern.
- Evidence: the highest monthly mean is {high_month['month']} ({high_month['mean']:,.2f}) and the lowest is {low_month['month']} ({low_month['mean']:,.2f}).
- Interpretation: the monthly pattern indicates a seasonal component, but it is not as structurally dominant as the weekday pattern in the current sample.
- Implication for Task 2.2: month is a sensible calendar candidate for later feature screening, while it should be treated as a complementary signal rather than a replacement for weekday and weekend effects.

## 5. What Does the Demand Distribution Look Like?

- Observation: the overall daily distribution is right-skewed, with a long upper tail and a visible separation between the central mass and the highest-demand days.
- Evidence: the mean ({df['daily_qty'].mean():,.2f}) is noticeably above the median ({df['daily_qty'].median():,.2f}), which is consistent with a skewed distribution.
- Interpretation: the shape suggests a heterogeneous daily-demand mixture, where the majority of days are moderate and a smaller set of days sit far into the upper tail.
- Implication for Task 2.2: the distribution supports retaining the original daily scale for supervised learning and checking whether a transformed or thresholded representation is needed only if later modeling evidence requires it.

## 6. How Should Outliers Be Interpreted?

- Observation: {len(outliers)} days are flagged by the same IQR rule used in Milestone 1.
- Evidence: the outlier dates are concentrated in a limited number of high-demand periods, and the outlier subset has an observed weekend share of {outlier_weekend_ratio:.2%}.
- Interpretation: there is no evidence these observations are invalid data points; they are more consistent with real high-demand business episodes. The current EDA therefore retains them rather than removing or correcting them.
- Implication for Task 2.2: outliers should remain visible during feature exploration and can be considered when evaluating whether holiday/weekend interactions or extreme-demand cases deserve dedicated logic, but they should not be treated as data errors without an external validation source.

## 7. Implications for Feature Engineering

1. The data covers a continuous daily period with no missing dates and is reliable for EDA.
2. Demand varies visibly by weekday, with a clear weekly pattern and a higher observed mean on the weekend.
3. Monthly demand also varies, indicating a weaker but still visible seasonal component.
4. The daily distribution is right-skewed, with a long upper tail and several extreme high-demand observations.
5. The IQR outliers are retained because there is no current evidence that they are erroneous data.
'''
    (BASE_DIR / 'M2_EDA_summary_task2.1.md').write_text(md, encoding='utf-8')


def main():
    args = parse_args()
    input_path = args.input.resolve()
    if not input_path.exists():
        raise FileNotFoundError(f'Input CSV not found: {input_path}')

    configure_style()
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    archive_redundant_outputs()

    df = load_data(input_path)
    outliers = detect_outliers(df)
    write_eda_summary(df, outliers)
    weekday_summary = write_weekday_summary(df)
    month_summary = write_month_summary(df)
    write_outlier_days(outliers)
    figure_daily_demand_trend(df, outliers)
    figure_weekday_distribution(df)
    figure_month_distribution(df)
    figure_daily_distribution(df)
    write_summary_md(df, outliers, weekday_summary, month_summary)

    core_questions = [
        'Q0. Is the dataset reliable enough for analysis?',
        'Q1. How does demand change over time?',
        'Q2. Does demand differ by weekday?',
        'Q3. Is there monthly seasonality?',
        'Q4. What does the demand distribution look like?',
        'Q5. How should outliers be interpreted?',
    ]
    core_figures = [
        '01_daily_demand_trend.png',
        '02_weekday_demand_distribution.png',
        '03_monthly_demand_distribution.png',
        '04_daily_demand_distribution.png',
    ]
    core_tables = [
        '01_eda_summary.csv',
        '02_weekday_summary.csv',
        '03_month_summary.csv',
        '04_outlier_days.csv',
    ]
    archived = sorted(p.name for p in ARCHIVE_DIR.iterdir() if p.is_file())
    print('Core questions')
    for q in core_questions:
        print('-', q)
    print('Generated core figures')
    for f in core_figures:
        print('-', f)
    print('Generated core tables')
    for t in core_tables:
        print('-', t)
    print('Main EDA findings')
    print('1. The daily dataset is continuous and suitable for analysis, with no missing dates and 1823 complete observations.')
    print('2. Daily demand shows visible time-varying structure with a sustained level and several high-demand episodes.')
    print('3. Weekday demand differs in a structured way, indicating a clear weekly calendar pattern and weekend-vs-weekday contrast.')
    print('4. Monthly demand also varies across the year, suggesting a weaker seasonal pattern that complements the weekday effect.')
    print('5. The distribution is right-skewed with a long upper tail, and the retained IQR outliers appear to represent real high-demand periods rather than data errors.')
    print('Archived redundant outputs')
    for item in archived:
        print('-', item)
    print('Validation result')
    print(f'Core figures count={len(list(FIG_DIR.iterdir()))}')
    print(f'Core tables count={len(list(TABLE_DIR.iterdir()))}')
    print('Source data modified: No')


if __name__ == '__main__':
    main()
